<script src="<%= request.getContextPath()%>/plugins/jquery/jquery.min.js"></script>
<script src="<%= request.getContextPath()%>/plugins/bootstrap/js/bootstrap.min.js"></script>
<script src="<%= request.getContextPath()%>/plugins/bootstrap-select/js/bootstrap-select.min.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
<script src="<%= request.getContextPath()%>/js/jquery-datatable.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-datatable/jquery.dataTables.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.min.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-datatable/extensions/export/jszip.min.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-datatable/extensions/export/pdfmake.min.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-datatable/extensions/export/vfs_fonts.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-datatable/extensions/export/buttons.html5.min.js"></script>
<script src="<%= request.getContextPath()%>/plugins/jquery-datatable/extensions/export/buttons.print.min.js"></script>
<script src="<%= request.getContextPath()%>/js/chartjs/Chart.bundle.js"></script>
<script src="<%= request.getContextPath()%>/js/jquery.countTo.js"></script>
<script src="<%= request.getContextPath()%>/js/admin.js"></script>
<script src="<%= request.getContextPath()%>/js/infobox-2.js"></script>
<!--<script src="<%= request.getContextPath()%>/js/charts/chartjs.js"></script>
<script src="<%= request.getContextPath()%>/js/charts/jquery-knob.js"></script>
<script src="<%= request.getContextPath()%>/js/charts/sparkline.js"></script>-->
<script src="<%= request.getContextPath()%>/plugins/node-waves/waves.min.js"></script>
<script src="<%= request.getContextPath()%>/js/jquery-ui.custom.min.js"></script>
<script src="<%= request.getContextPath()%>/js/consultar-dados.js" type="text/javascript"></script>
<script src="<%= request.getContextPath()%>/js/masc.js"></script>